### PR TITLE
Add a config for AppVeyor

### PR DESCRIPTION
**Pull request by schwern**
http://www.appveyor.com/ is continuous integration testing for Windows. utf8::all would do well to use it.

It's not nearly as simple as Travis. This adds a config file for AppVeyor to test against Strawberry Perl. You'll need to sign up and turn it on.

### CODE REVIEW

**Comment by HayoBaan** [comment]
Hi Michael,
What would be the benefit of this test over the CPAN testing that is already being performed?
(besides, CPAN testing has the advantage it is multi platform, not just windows)

**Comment by schwern** [comment]
CPAN testing is great, and this does not conflict with that. It has all the same benefits of any continuous integration testing, like Travis. Now you have it for Windows.

Like Travis, the main advantage of AppVeyor is it happens *before* release. ([For example, I recently broke Text::Metaphone on Windows](http://matrix.cpantesters.org/?dist=Text-Metaphone%2020160804)) by unknowingly rolling back an old Windows fix. AppVeyor would have caught that, and I'm now adding it to all my projects.

As with any CI testing, you get the results per-commit. You know within a few minutes which commit broke something. This makes debugging easier. With CPAN testers you just know something in the release broke.

It happens for all contributions. Not everyone has Windows available, and even if they do, people often forget to run the tests on Windows.

It greatly reduces the Windows debugging cycle for all contributors. They can post a PR, see its broken on Windows, and try to debug it. No Windows setup required. No waiting for a release or some other contributor to maybe remember to try it on Windows.

And its free.

**Comment by HayoBaan** [comment]
OK, sounds beneficial. So apart from merging your pull request, what do I need to do to have this set up?

**Comment by schwern** [comment]
1. Signup at https://ci.appveyor.com/signup, probably with your Github account.
2. Link to your Github account (you can skip this if you signed up with it).
3. Go to https://ci.appveyor.com/projects
4. Click "New project".
5. Find doherty -> utf8-all in the list.
6. Click `(+) Add` waaaay over on the right side (the UI isn't the best).
7. Verify the AppVeyor webhook got installed in https://github.com/doherty/utf8-all/settings/hooks

In my experience if you don't own the project, it might not add the webhook and thus won't see new commits. You can manually add it, get the webhook URL from your AppVeyor project settings. You'll want to enable it for pull requests and pushes.

**Comment by HayoBaan** [comment]
Adding appveyor seems to have worked, I can not verify if the hook got installed though. I get a 404 page error on your link and when I check my own settings I can not find the “hooks” you refer to (two appveyor apps are authorised though, so that has worked).

Any thoughts?

**Comment by schwern** [comment]
As a collaborator on a personal repository, you might not have access to the Github repository settings. Using an organization gives more control, that's why I have evalEmpire.

But it looks like it worked! https://ci.appveyor.com/project/HayoBaan/utf8-all

**Comment by HayoBaan** [comment]
The report is there because I manually started the build. But you're right, because I am not the owner, I can not change the settings (so neither the webhooks). I'll see what can be done about this.

**Pull request merged**
