### PR TITLE
Use PerlIO::utf8_strict as the default.

### PR DESCRIPTION
**Pull request by schwern**
Leon suggested using PerlIO::utf8_strict as the default.
https://github.com/doherty/utf8-all/issues/42#issuecomment-238928373

It seems to work.

I'm assuming there's still value in trying to use `:encoding(UTF-8)`?
Maybe it's faster? @Leont could you comment?

### CODE REVIEW

**Comment by Leont** [comment]
`:utf8_strict` is faster and stricter (it never recodes to replacement character U+FFFD but throw an error when decoding a invalid byte sequence), but unlike :utf8 it doesn't work well on layers without buffer peeking (such as `:stdio`), but that's not an issue in our case (and just as much an issue in `:encoding`).

**Comment by schwern** [comment]
@Leont Soooo... is it ok to always use `:utf8_strict`?

**Comment by schwern** [comment]
@Leont Any idea what's happening here? https://travis-ci.org/doherty/utf8-all/jobs/151371914

**Comment by HayoBaan** [comment]
> Any idea what's happening here? https://travis-ci.org/doherty/utf8-all/jobs/151371914

I saw this in the CPAN reports too. It's unrelated to this change. I'll have a look at this after I finish integrating PerlIO::utf8_strict.

**Comment by HayoBaan** [comment]
I have fixed the build errors! All that was needed was a ``no warnings FATAL => 'utf8';``. Interesting that only for some versions of Perl, the illegal \x{d800} caused this…

**Pull request merged**
