### PR TITLE
Imlementation of “no utf8::all” 

### PR DESCRIPTION
**Pull request by HayoBaan**
This is the implementation of “no utf8::all”. Fixes some tests as well.

### CODE REVIEW

**Comment by doherty** [comment]
Merging this caused tests to start failing `:\`

````
$ prove
./t/ARGV.t ............. ok   
./t/ARGV_nonmain.t ..... ok   
./t/ARGV_twice.t ....... ok   
./t/FATAL_utf8.t ....... ok   
./t/autodie.t .......... ok   
./t/charnames.t ........ ok   
./t/fc.t ............... ok   
./t/glob.t ............. ok   
./t/lexical-again.t .... 1/17 
#   Failed test 'octets retreived OK'
#   at ./t/lexical-again.t line 24.
Wide character in print at /home/mike/perl5/perlbrew/perls/perl-5.22.0/lib/5.22.0/Test/Builder.pm line 1826, <$in> line 1.
#          got: 'テスト
# '
#     expected: 'ãã¹ã
# '

#   Failed test 'IN: utf8 does not appear in the perlio layers'
#   at ./t/lexical-again.t line 31.
# {
#   'IN' => [
#     'unix',
#     'perlio',
#     'encoding(utf-8-strict)',
#     'utf8'
#   ]
# }

#   Failed test 'IN: utf-8-strict does not appear in the perlio layers'
#   at ./t/lexical-again.t line 33.
# {
#   'IN' => [
#     'unix',
#     'perlio',
#     'encoding(utf-8-strict)',
#     'utf8'
#   ]
# }

#   Failed test 'OUT: utf8 does not appear in the perlio layers'
#   at ./t/lexical-again.t line 31.
# {
#   'OUT' => [
#     'unix',
#     'perlio',
#     'encoding(utf-8-strict)',
#     'utf8'
#   ]
# }

#   Failed test 'OUT: utf-8-strict does not appear in the perlio layers'
#   at ./t/lexical-again.t line 33.
# {
#   'OUT' => [
#     'unix',
#     'perlio',
#     'encoding(utf-8-strict)',
#     'utf8'
#   ]
# }
# Looks like you failed 5 tests of 17.
./t/lexical-again.t .... Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/17 subtests 
./t/lexical.t .......... ok   
./t/open.t ............. ok   
./t/readdir.t .......... ok   
./t/readlink.t ......... ok   
./t/readpipe.t ......... ok   
./t/unicode_eval.t ..... ok   
./t/unicode_strings.t .. ok     
./t/utf8.t ............. ok    

Test Summary Report
-------------------
./t/lexical-again.t  (Wstat: 1280 Tests: 17 Failed: 5)
  Failed tests:  5-9
  Non-zero exit status: 5
Files=17, Tests=87,  1 wallclock secs ( 0.06 usr  0.00 sys +  0.59 cusr  0.03 csys =  0.68 CPU)
Result: FAIL
````

some of which seems bogus (utf8/utf-8-strict *is* there).

**Comment by HayoBaan** [comment]
Right, from what the test are telling me, the `no utf8::all` failed to remove the utf8 layers from I/O completely. (The test description is a bit confusing; it means that there should be *no* utf8 layers present, but that it failed that condition). Anyway, my guess is that on your perl version (I'm on v5.18) the statement `'open'->import::into($target, qw{:std});` (line 166 of all.pm) does not suffice to get rid of the utf8 encoding layers. Hmm…
I guess something has changed in the perl implementation in this respect, meaning we need to find another way to do this. Any ideas?

**Comment by HayoBaan** [comment]
I think I have a solution for the issue: instead of `'open'->import::into($target, qw{:std});`, we can also use
`'open'->import::into($target, qw{IO :bytes});`. Can you see if that works for you too?

**Comment by HayoBaan** [comment]
Hi Mike, I have created a pull request for my proposed change. It should work for you too now (at least according to the perl documentation…)

**Pull request merged**
