### PR TITLE
Added wrapper for readlink [gh-21]

### PR DESCRIPTION
**Pull request by HayoBaan**
Found some time to implement this relatively straightforward addition to the core set.
I think that concludes all doable / non-dangerous core functions that need to be wrapped.

### CODE REVIEW

**Comment by HayoBaan** [comment]
Right, as already discussed in [gh-21], it turned out `readpipe` etc. already worked as expected. I created a test for it nonetheless and rewrote the documentation as well (hope you like my changes and that everything is now even more clear than before).

My next little project for `utf8::all` will be the implementation of `no utf8::all`…

**Comment by doherty** [comment]
When running the new readpipe test, I consistently get the following failure:
```
$ prove t/readpipe.t 
t/readpipe.t .. 1/9 
#   Failed test 'readpipe utf8 result should be as expected'
#   at t/readpipe.t line 30.
Wide character in print at /home/mike/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Test/Builder.pm line 1825.
#          got: 'みかちゃん
# testfile
# '
#     expected: 'testfile
# みかちゃん
# '

#   Failed test 'Backtick utf8 result should be as expected'
#   at t/readpipe.t line 30.
Wide character in print at /home/mike/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Test/Builder.pm line 1825.
#          got: 'みかちゃん
# testfile
# '
#     expected: 'testfile
# みかちゃん
# '

#   Failed test 'qx utf8 result should be as expected'
#   at t/readpipe.t line 30.
Wide character in print at /home/mike/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/Test/Builder.pm line 1825.
#          got: 'みかちゃん
# testfile
# '
#     expected: 'testfile
# みかちゃん
# '
# Looks like you failed 3 tests of 9.
t/readpipe.t .. Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/9 subtests 

Test Summary Report
-------------------
t/readpipe.t (Wstat: 768 Tests: 9 Failed: 3)
  Failed tests:  1, 4, 7
  Non-zero exit status: 3
Files=1, Tests=9,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.07 cusr  0.04 csys =  0.15 CPU)
Result: FAIL
```

Are you sure the pipe through sort is correct? When I add the `-r` flag to sort in reverse, the test passes. You might consider providing a sort option to `ls` directly, perhaps `-t` to sort by mtime, since we know when the entries were created (relative to one another).

**Comment by HayoBaan** [comment]
Weird that sort on your system sorts unicode differently. Anyway, I have now changed the test so it should always work.
When you're Ok with this one, I already have the `no utf8::all` pragma implemented :smiley:

**Comment by doherty** [comment]
Apologies for the long wait.

**Comment by HayoBaan** [comment]
No worries! I know how crazy busy things can be.
I will create the pull request for the `no utf8::all` in a minute so perhaps you can have a look at that one too :smiley:

**Pull request merged**
